name: staging

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish project
      run: dotnet publish -c release
      working-directory: ./src/BikeDataProject.Integrations.Fitbit/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bikedataproject/fitbit-integration-api:staging
      working-directory: ./src/BikeDataProject.Integrations.Fitbit/
    - name: Login to Dock Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u xivk --password-stdin
    - name: Publish the image to GitHub packages.
      run: docker push bikedataproject/fitbit-integration-api:staging
      working-directory: ./src/BikeDataProject.Integrations.Fitbit/
